Vagrant.configure("2") do |config|
    # Configure ubuntu machine
    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = "Kontowicz/Ubuntu20.04"
        ubuntu.vm.box_version = "0.0.1"
        ubuntu.vm.network "private_network", ip: "192.168.56.41"
        ubuntu.vm.hostname = "spinaker-ubuntu-big-data"
        ubuntu.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = 2
            vb.gui = true
        end
        ubuntu.vm.provision "shell", path: "config/ubuntu.sh", privileged: "true"  
    end       
end