Vagrant.configure("2") do |config|
    # Configure Win10 crypto machine
    config.vm.define "win10" do |win|
        win.vm.box = "Kontowicz/Win10_crypto"
        win.vm.box_version = "0.0.1"
        win.vm.network "private_network", ip: "192.168.56.21"
        win.vm.hostname = "spinaker-win-crypto"
        win.vm.provider "virtualbox" do |vb|
            vb.name = "Windows 10 Crypto"
            vb.memory = "4096"
            vb.cpus = 2
            vb.gui = true
        end
    end
end